name: DAG Validate
on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'dags/**'
      - '**/dags/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install Python Dependencies
      run: pip install pyyaml

    - name: Run Validate DAG code
      run: python -m unittest generate_dag/tests/test_generate_dag.py

    - name: Show DAG validation report
      if: success() || failure()
      run: cat /tmp/validation_report.yaml

    - name: Informational error message
      if: failure()
      run: |
        echo "Please, make sure DAG config is aligned with actual DAG code"
        echo "If it is custom case you can add pipeline name in generate_dag/validate_config.yaml under exclude"
